### ISSUE TITLE
Question:  Business flow control

### ISSUE THREAD

**Issue by MostafaEsmaeili** [rabbal/DNTFrameworkCore#1]
hello.
I want to use services to implement my business logic flow. For example, I want to use Accounting Service and SaleService to implement the order flow(check balance, etc). I want to know your recommended way to do this by this framework. 
Thanks.

**Comment by rabbal** [comment]
**Note:** based on this infrastructure's services and CRUD-based thinking behind them, each command must be crossed from entity related service (business). for example if you want to let users remove an OrderItem from Order in front-office, you can't manually remove one single OrderItem from your storage. for this situation, you must fetch entire Order with OrderService.FindAsync(orderId) and then mark that OrderItem as Deleted then use OrderService.EditAsync(model) to update that aggregate root with related entites like OrderItem. 

In your scenario and similar scenarios, you can query from every repository (IUnitOfWork.Set<TEntity>) without any limitation everywhere. I mean you can inject IUnitOfWork in OrderValidator and implement your business rules or encapsulate these rules in IOrderRules and then inject it OrderValidator.

Also, instead of Validator, you can override [BeforeCreateAsync ](https://github.com/rabbal/DNTFrameworkCore/blob/master/src/DNTFrameworkCore.EntityFramework/Application/CrudService.cs#L179) and [BeforeEditAsync](https://github.com/rabbal/DNTFrameworkCore/blob/master/src/DNTFrameworkCore.EntityFramework/Application/CrudService.cs#L240) virtual methods in OrderService.

**Comment by MostafaEsmaeili** [comment]
OK. Thank but is there any way to use services instead of directly use (`IUnitOfWork.Set<TEntity>`)  ?

**Comment by rabbal** [comment]
There is no limitation, you can expose some methods from AccountingService and SaleService and then use them in OrderValidator/OrderService/OrderRules. I mean, services can refer to each other.

**Comment by MostafaEsmaeili** [comment]
Thanks  GholamReza .
